# Generated by Django 4.0.3 on 2022-07-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingInventoryVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('product', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventoryVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('product', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('subscriptions', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_items', models.ManyToManyField(related_name='products', to='subscriptions_rest.productinventoryvo')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clothing_items', models.ManyToManyField(related_name='clothing', to='subscriptions_rest.clothinginventoryvo')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=False, related_name='subscription', serialize=False, to='subscriptions_rest.user')),
                ('model_number', models.PositiveSmallIntegerField(unique=True)),
                ('price', models.PositiveSmallIntegerField(default=30)),
                ('clothing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='subscriptions_rest.clothingbox')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='subscriptions_rest.productsbox')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(unique=True)),
                ('price', models.CharField(default='$36.99', max_length=50)),
                ('description', models.CharField(default='Here are your items', max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='subscriptions_rest.user')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='subscriptions_rest.subscription')),
            ],
        ),
    ]
