# Generated by Django 4.0.3 on 2022-08-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_rest', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='username',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
