# Generated by Django 4.0.3 on 2022-08-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_rest', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothinginventoryvo',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productinventoryvo',
            name='sku',
        ),
        migrations.AddField(
            model_name='clothinginventoryvo',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinventoryvo',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
