# Generated by Django 4.0.3 on 2022-08-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_rest', '0003_receipt_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='model_number',
            new_name='modelnumber',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='order_number',
            new_name='orderNumber',
        ),
        migrations.AddField(
            model_name='receipt',
            name='zip',
            field=models.CharField(default=77777, max_length=254),
            preserve_default=False,
        ),
    ]
