# Generated by Django 4.0.3 on 2022-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_rest', '0004_rename_first_name_receipt_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='orderNumber',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
