# Generated by Django 4.0.3 on 2022-08-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_rest', '0005_alter_receipt_ordernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='modelnumber',
        ),
    ]
