# Generated by Django 4.0.3 on 2022-07-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_rest', '0002_remove_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, choices=[('1', 'Small'), ('2', 'Medium'), ('3', 'Large'), ('4', 'XLarge'), ('5', 'XXLarge')], default='3', max_length=8, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_inventory', to='products_rest.product_category')),
            ],
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
    ]
