# Generated by Django 4.0.3 on 2022-07-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_rest', '0003_clothing_inventory_delete_clothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing_inventory',
            name='size',
            field=models.CharField(blank=True, choices=[('1', 'Small'), ('Medium', 'M'), ('3', 'Large'), ('4', 'XLarge'), ('5', 'XXLarge')], default='3', max_length=8, null=True),
        ),
    ]
