# Generated by Django 4.0.3 on 2022-07-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_rest', '0004_alter_clothing_inventory_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing_inventory',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('XLarge', 'Xl'), ('XXLarge', 'Xx')], default='Large', max_length=8, null=True),
        ),
    ]
