# Generated by Django 4.0.3 on 2022-07-14 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products_rest', '0005_alter_clothing_inventory_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing_inventory',
            name='id',
        ),
        migrations.AddField(
            model_name='clothing_inventory',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
