# Generated by Django 4.0.3 on 2022-08-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_rest', '0006_remove_clothing_inventory_id_clothing_inventory_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
