# Generated by Django 4.0.3 on 2022-08-02 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_rest', '0007_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture_url', models.URLField()),
                ('description', models.TextField(max_length=1024)),
                ('clothing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_category', to='products_rest.product_category')),
            ],
        ),
    ]
